stages:

  clean:
    cmd: python src/clean.py
    deps:
      - data/raw/telco_customer_churn.csv
    outs:
      - data/processed/telco_customer_churn_clean.csv

  features:
    cmd: python src/features.py
    deps:
      - data/processed/telco_customer_churn_clean.csv
    outs:
      - data/features/telco_customer_churn_features.csv

  train:
    cmd: python src/train.py
    deps:
      - data/features/telco_customer_churn_features.csv
    outs:
      - models/random_forest_model.pkl